version: '3'
services:
  db:
    image: mysql
    container_name: rails_db
    environment:
      - MYSQL_ROOT_PASSWORD=sample
      - MYSQL_PASSWORD=sample
      - MYSQL_USER=sample
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: rails_web
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - vendor_bundle:/user/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_DATABASE_USERNAME=root
      - RAILS_DATABASE_PASSWORD=sample
      - RAILS_DATABASE_NAME=sample
      - RAILS_DATABASE_HOST=rails_db
    tty: true
    stdin_open: true
volumes:
  vendor_bundle:
    driver: local
